spring.application.name=Doctor_Letter

jwt.secret=ThisIsASecretKeyThatIsAtLeast256BitsLongForHmacSha256AlgorithmUsedInJwtSigning1234567890
jwt.access-token-expiry=900000
jwt.refresh-token-expiry=604800000
